APPLY_FIXES: all
DEFAULT_BRANCH: main
# We use the .graphql extension for queries, not schemas, for the sake of syntax
# highlighting.
DISABLE_LINTERS: GRAPHQL_GRAPHQL_SCHEMA_LINTER
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FORMATTERS_DISABLE_ERRORS: false
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .md
JSON_ESLINT_PLUGIN_JSONC_PRE_COMMANDS:
  # See https://github.com/nvuillam/mega-linter/issues/773.
  - command: npm install eslint-plugin-jsonc@1.7.0
PYTHON_FLAKE8_PRE_COMMANDS:
  - command: pip install flake8-bugbear==21.9.2 mccabe==0.6.1
PYTHON_ISORT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_MYPY_CONFIG_FILE: LINTER_DEFAULT
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
