APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DEFAULT_BRANCH: main
DISABLE_LINTERS:
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER # We have .graphql queries, not schemas.
  - MARKDOWN_MARKDOWN_LINK_CHECK # Superseded by Lychee
  - PYTHON_FLAKE8 # Superseded by Ruff
  - PYTHON_ISORT # Superseded by Ruff
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
JSON_PRETTIER_FILE_EXTENSIONS:
  - .graphql
  - .json
  - .md
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_MYPY_CONFIG_FILE: LINTER_DEFAULT
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_RUFF_CONFIG_FILE: LINTER_DEFAULT
REPOSITORY_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
