APPLY_FIXES: all
CLEAR_REPORT_FOLDER: true
DEFAULT_BRANCH: main
# We use the .graphql extension for queries, not schemas, for the sake of syntax
# highlighting.
DISABLE_LINTERS:
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
FORMATTERS_DISABLE_ERRORS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
CREDENTIALS_SECRETLINT_ARGUMENTS: --secretlintignore .gitignore
JSON_PRETTIER_FILE_EXTENSIONS:
  - .graphql
  - .json
  - .md
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml
PYTHON_FLAKE8_PRE_COMMANDS:
  # Keep in sync with pyproject.toml.
  - command: pip install flake8-bugbear==23.3.12 mccabe==0.7.0
PYTHON_ISORT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_MYPY_CONFIG_FILE: LINTER_DEFAULT
PYTHON_PYLINT_CONFIG_FILE: LINTER_DEFAULT
SPELL_CSPELL_CONFIG_FILE: LINTER_DEFAULT
