default_install_hook_types:
  - commit-msg
  - post-checkout
  - post-rewrite
  - pre-commit
  - pre-merge-commit
  - pre-push
default_language_version:
  python: python3.9.7 # Keep in sync with .tool-versions and pyproject.toml.
default_stages:
  - commit
  - push
minimum_pre_commit_version: 2.18.1
repos:
  # Automatically fix issues.

  ## Python, Polyglot, Git, pre-commit
  - repo: https://github.com/ScribeMD/pre-commit-hooks
    rev: 0.8.0
    hooks:
      - id: no-merge-commits
      - id: asdf-install
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
      - id: pre-commit-install
      - id: megalinter
        args:
          - --env
          - "'DISABLE_LINTERS=COPYPASTE_JSCPD,GRAPHQL_GRAPHQL_SCHEMA_LINTER'"
          - --flavor
          - python
          - --release
          - v5.16.1
      - id: megalinter-all
        args: [--flavor, python, --release, v5.16.1]

  ## Python
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--wrap-summaries, "88", --wrap-descriptions, "88"]

  ## Markdown
  - repo: https://github.com/frnmst/md-toc
    rev: 8.1.4
    hooks:
      - id: md-toc

  ## Python, TOML, Polyglot, Git
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      ### Automatically fix issues.
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: \.dictionary\.txt
        args: [--ignore-case, --unique]
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]

      ### Check for issues.
      - id: check-added-large-files
        args: [--enforce-all]
      - id: check-ast
      - id: check-builtin-literals
        args: [--no-allow-dict-kwargs]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: name-tests-test
      - id: no-commit-to-branch

  # Check for issues.

  ## Pre-commit
  - repo: meta
    hooks:
      - id: check-useless-excludes

  ## Python
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - toml==0.10.2
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check

  ## Natural language
  - repo: https://github.com/PrincetonUniversity/blocklint
    rev: v0.2.3
    hooks:
      - id: blocklint

  ## Git
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.1 # Keep in sync with pyproject.toml.
    hooks:
      - id: commitizen
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: check-mailmap
      - id: forbid-binary
      - id: git-check
