name: Bump Version
on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      SLACK_BOT_TOKEN:
        description: >
          The Slack API bot token for your custom app. It will be used to report
          the result of the workflow. The token must have the chat:write scope.
        required: true
      SLACK_ACTIONS_CHANNEL_ID:
        description: >
          The ID of the Slack channel to report the workflow result to. Your bot
          should be a member. Secondary-click on the channel in Slack, and
          select "Copy link" to copy a URL containing the channel ID.
        required: true
jobs:
  bump-version:
    name: Bump Version
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository.
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0
      - name: Push a commit to main to bump version and update changelog.
        uses: commitizen-tools/commitizen-action@0.12.0
        with:
          branch: main
          git_name: commitizen-github-action[bot]
          git_email: commitizen-github-action[bot]@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commitizen_version: 2.24.0 # Keep in sync with pyproject.toml.
      - name: Send Slack notification with job status (self-test).
        if: ${{ github.repository == 'ScribeMD/slack-templates' }}
        uses: ./
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
          template: result
      - name: Send Slack notification with job status (called workflow).
        if: ${{ github.repository != 'ScribeMD/slack-templates' }}
        uses: ScribeMD/slack-templates@main
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
          template: result
