name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write # for pre-commit-action
jobs:
  test:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository.
        uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0
      - name: Run pre-commit hooks.
        uses: ScribeMD/pre-commit-action@0.9.64
      - name: Send Slack notification with job status.
        if: always()
        uses: ./
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_ACTIONS_CHANNEL_ID }}
          template: result
